table_data = [{'bar_cod': '1', 'name': 'Alho francês', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 1.2,
               'quantity': 1500.0,
               'description': 'Alho francês', 'photo': 'alho_frances.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '2', 'name': 'Tomate', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 0.89,
               'quantity': 2500.0,
               'description': 'Tomate', 'photo': 'tomate.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '3', 'name': 'Curgete', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 1.48,
               'quantity': 590.0,
               'description': 'Curgete', 'photo': 'curgete.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '4', 'name': 'Cenoura', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 0.72,
               'quantity': 234.0,
               'description': 'Cenoura', 'photo': 'cenoura.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '5', 'name': 'Alface', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 0.48,
               'quantity': 25.0,
               'description': 'Alface', 'photo': 'alface.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '6', 'name': 'Espargos', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 2.99,
               'quantity': 80.0,
               'description': 'Espargos', 'photo': 'espargos.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '7', 'name': 'Feijão Verde', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 1.99,
               'quantity': 120.0,
               'description': 'Feijão Verde', 'photo': 'feijão_verde.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '8', 'name': 'Couve Coração', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 0.98,
               'quantity': 50.0,
               'description': 'Couve Coração', 'photo': 'couve_coração.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '9', 'name': 'Couve Roxa', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 1.29,
               'quantity': 20.0,
               'description': 'Couve Roxa', 'photo': 'couve_roxa.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '10', 'name': 'Cebola', 'name_1': 'Propria', 'name_2': 'Vegetais', 'price': 0.78,
               'quantity': 2500.0,
               'description': 'Cebola', 'photo': 'cebola.png', 'id': 1, 'id_1': 19},
              {'bar_cod': '11', 'name': 'Banana', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 0.98,
               'quantity': 150.0,
               'description': 'Banana', 'photo': 'banana.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '12', 'name': 'Morango', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 5.0,
               'quantity': 80.0,
               'description': 'Morango', 'photo': 'morango.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '13', 'name': 'Manga', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 2.9,
               'quantity': 290.0,
               'description': 'Manga', 'photo': 'manga.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '14', 'name': 'Papaia', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 3.9,
               'quantity': 487.0,
               'description': 'Papaia', 'photo': 'papaia.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '15', 'name': 'Ananás', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 2.4,
               'quantity': 342.0,
               'description': 'Ananás', 'photo': 'ananas.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '16', 'name': 'Uva', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 1.5, 'quantity': 756.0,
               'description': 'Uva', 'photo': 'uva.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '17', 'name': 'Kiwi', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 1.5, 'quantity': 233.0,
               'description': 'Kiwi', 'photo': 'kiwi.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '18', 'name': 'Kiwi Amarelo', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 6.0,
               'quantity': 132.0,
               'description': 'Kiwi Amarelo', 'photo': 'kiwi_amarelo.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '19', 'name': 'Maçã Golden', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 1.2,
               'quantity': 123.0,
               'description': 'Maçã Golden', 'photo': 'maçã_goden.png', 'id': 2, 'id_1': 19},
              {'bar_cod': '20', 'name': 'Maçã Fuji', 'name_1': 'Propria', 'name_2': 'Fruta', 'price': 1.5,
               'quantity': 1222.0,
               'description': 'Maçã Fuji', 'photo': 'maça_fuji.png', 'id': 2, 'id_1': 19}]
